# Generated by Django 4.2.30 on 2026-07-08 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOWorkspace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Legal Name')),
                ('cin', models.CharField(blank=True, max_length=21, null=True, verbose_name='Corporate Identity Number (CIN)')),
                ('exchange_target', models.CharField(choices=[('nse_emerge', 'NSE Emerge (SME)'), ('bse_sme', 'BSE SME')], default='nse_emerge', max_length=50, verbose_name='Target Exchange')),
                ('status', models.CharField(choices=[('draft', 'Draft — Data Entry in Progress'), ('review', 'Under Review'), ('submitted', 'Submitted to Merchant Banker')], default='draft', max_length=30)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_workspace', to='db.workspace')),
            ],
            options={
                'verbose_name': 'IPO Workspace',
                'verbose_name_plural': 'IPO Workspaces',
                'db_table': 'trinity_ipo_workspaces',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ObjectsOfIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fresh_issue_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Schedule VI, Part A, Clause 2(1)(a)', max_digits=15, null=True, verbose_name='Fresh Issue Amount (₹ in Lakhs)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ipo_workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objects_of_issue', to='trinity.ipoworkspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Objects of the Issue',
                'verbose_name_plural': 'Objects of the Issue',
                'db_table': 'trinity_objects_of_issue',
            },
        ),
        migrations.CreateModel(
            name='UseOfProceeds',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(choices=[('capex', 'Capital Expenditure'), ('working_capital', 'Working Capital'), ('general_corporate_purposes', 'General Corporate Purposes'), ('debt_repayment', 'Debt Repayment'), ('other', 'Other')], help_text='Schedule VI, Part A, Clause 2(1)(b)', max_length=50, verbose_name='Use of Proceeds Category')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 2(1)(a)', max_digits=15, verbose_name='Amount (₹ in Lakhs)')),
                ('justification', models.TextField(help_text='Schedule VI, Part A, Clause 2(1)(c)', verbose_name='Justification / Rationale')),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('objects_of_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_of_proceeds', to='trinity.objectsofissue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Use of Proceeds',
                'verbose_name_plural': 'Use of Proceeds',
                'db_table': 'trinity_use_of_proceeds',
                'ordering': ('sort_order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ShareholderEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('shareholder_name', models.CharField(help_text='Schedule VI, Part A, Clause 5(a)', max_length=255, verbose_name='Shareholder Name')),
                ('category', models.CharField(choices=[('promoter', 'Promoter'), ('promoter_group', 'Promoter Group'), ('public', 'Public Shareholder')], help_text='Schedule VI, Part A, Clause 5(b)', max_length=20, verbose_name='Shareholder Category')),
                ('number_of_shares', models.PositiveBigIntegerField(help_text='Schedule VI, Part A, Clause 5(c)', verbose_name='Number of Equity Shares')),
                ('percentage_holding', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 5(c)', max_digits=6, verbose_name='Percentage Holding (%)')),
                ('date_of_acquisition', models.DateField(help_text='Schedule VI, Part A, Clause 5(d)', verbose_name='Date of Acquisition / Allotment')),
                ('acquisition_price_per_share', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 5(d)', max_digits=12, verbose_name='Acquisition Price per Share (₹)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ipo_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='trinity.ipoworkspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Shareholder Entry',
                'verbose_name_plural': 'Shareholder Entries',
                'db_table': 'trinity_shareholder_entries',
                'ordering': ('category', 'shareholder_name'),
            },
        ),
        migrations.CreateModel(
            name='RelatedPartyTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('related_party_name', models.CharField(help_text='Schedule VI, Part A, Clause 14(a)', max_length=255, verbose_name='Related Party Name')),
                ('relationship_type', models.CharField(choices=[('promoter', 'Promoter'), ('promoter_group', 'Promoter Group Entity'), ('director', 'Director'), ('key_management_personnel', 'Key Management Personnel'), ('subsidiary', 'Subsidiary Company'), ('associate', 'Associate Company'), ('joint_venture', 'Joint Venture'), ('relative_of_director', 'Relative of Director/KMP'), ('entity_with_common_control', 'Entity under Common Control'), ('other', 'Other Related Party')], help_text='Schedule VI, Part A, Clause 14(b)', max_length=50, verbose_name='Relationship Type')),
                ('transaction_type', models.CharField(help_text='Schedule VI, Part A, Clause 14(c)', max_length=255, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 14(d)', max_digits=15, verbose_name='Transaction Amount (₹ in Lakhs)')),
                ('financial_year', models.CharField(help_text='Format: YYYY-YYYY (e.g., 2023-2024)', max_length=9, verbose_name='Financial Year')),
                ('is_arms_length', models.BooleanField(default=True, help_text='Schedule VI, Part A, Clause 14(e)', verbose_name="At Arm's Length?")),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ipo_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_party_transactions', to='trinity.ipoworkspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Related Party Transaction',
                'verbose_name_plural': 'Related Party Transactions',
                'db_table': 'trinity_related_party_transactions',
                'ordering': ('-financial_year', 'related_party_name'),
            },
        ),
        migrations.CreateModel(
            name='LitigationEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('case_type', models.CharField(choices=[('criminal', 'Criminal Proceedings'), ('civil', 'Civil Litigation'), ('regulatory', 'Regulatory Actions'), ('tax', 'Tax Proceedings')], help_text='Schedule VI, Part A, Clause 17(a)', max_length=20, verbose_name='Case Type')),
                ('party_involved', models.CharField(help_text='Schedule VI, Part A, Clause 17(b)', max_length=500, verbose_name='Party Involved')),
                ('court_or_authority', models.CharField(help_text='Schedule VI, Part A, Clause 17(c)', max_length=500, verbose_name='Court / Authority / Forum')),
                ('status', models.CharField(help_text='Schedule VI, Part A, Clause 17(d)', max_length=1000, verbose_name='Current Status')),
                ('amount_involved', models.DecimalField(blank=True, decimal_places=2, help_text='Schedule VI, Part A, Clause 17(e)', max_digits=15, null=True, verbose_name='Amount Involved (₹ in Lakhs)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ipo_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litigations', to='trinity.ipoworkspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Litigation Entry',
                'verbose_name_plural': 'Litigation Entries',
                'db_table': 'trinity_litigation_entries',
                'ordering': ('case_type', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FinancialYearSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('financial_year', models.CharField(help_text='Format: YYYY-YYYY (e.g., 2023-2024). Schedule VI, Part A, Clause 10(a).', max_length=9, verbose_name='Financial Year')),
                ('revenue', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 10(b)', max_digits=15, verbose_name='Revenue from Operations (₹ in Lakhs)')),
                ('ebitda', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 10(c)', max_digits=15, verbose_name='EBITDA (₹ in Lakhs)')),
                ('pat', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 10(d)', max_digits=15, verbose_name='Profit After Tax (₹ in Lakhs)')),
                ('net_worth', models.DecimalField(decimal_places=2, help_text='Schedule VI, Part A, Clause 10(e), read with Regulation 229(2)(b)', max_digits=15, verbose_name='Net Worth (₹ in Lakhs)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ipo_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_summaries', to='trinity.ipoworkspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Financial Year Summary',
                'verbose_name_plural': 'Financial Year Summaries',
                'db_table': 'trinity_financial_year_summaries',
                'ordering': ('-financial_year',),
            },
        ),
        migrations.AddConstraint(
            model_name='financialyearsummary',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('ipo_workspace', 'financial_year'), name='trinity_fy_summary_unique_workspace_fy_when_not_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='financialyearsummary',
            unique_together={('ipo_workspace', 'financial_year', 'deleted_at')},
        ),
    ]
