# Generated by Django 4.2.30 on 2026-07-08 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trinity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('rule_id', models.CharField(help_text="Machine-readable rule identifier, e.g., 'rpt_single_party_threshold'.", max_length=100, verbose_name='Rule Identifier')),
                ('severity', models.CharField(choices=[('blocking', 'Blocking — must be resolved before submission'), ('warning', 'Warning — review recommended'), ('info', 'Informational — for awareness')], max_length=10, verbose_name='Severity Level')),
                ('section', models.CharField(help_text='Which disclosure section this flag pertains to.', max_length=60, verbose_name='DRHP Section')),
                ('field_reference', models.CharField(blank=True, default='', help_text='Specific field(s) or record(s) involved.', max_length=255, verbose_name='Field Reference')),
                ('message', models.TextField(help_text='Human-readable explanation of the flag.', verbose_name='Flag Message')),
                ('regulation_citation', models.CharField(help_text='ICDR clause or SEBI regulation reference.', max_length=255, verbose_name='Regulation Citation')),
                ('related_data', models.JSONField(blank=True, default=dict, help_text='Structured data: actual figures, thresholds, entity names.', verbose_name='Related Data')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ipo_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_flags', to='trinity.ipoworkspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Validation Flag',
                'verbose_name_plural': 'Validation Flags',
                'db_table': 'trinity_validation_flags',
                'ordering': ('severity', 'section', '-created_at'),
            },
        ),
    ]
