# Generated by Django 4.2.30 on 2026-07-09 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trinity', '0002_validationflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('section', models.CharField(choices=[('objects_of_issue', 'Objects of the Issue'), ('related_party_transactions', 'Related Party Transactions')], max_length=60, verbose_name='DRHP Section')),
                ('version', models.PositiveIntegerField(help_text='Auto-incremented per workspace + section.', verbose_name='Draft Version')),
                ('narrative_text', models.TextField(help_text='The LLM-generated prose text for this section.', verbose_name='Generated Narrative')),
                ('prompt_template_version', models.CharField(help_text="Which versioned template was used (e.g., 'v1').", max_length=20, verbose_name='Prompt Template Version')),
                ('data_snapshot', models.JSONField(default=dict, help_text='Complete snapshot of the structured data fed to the LLM.', verbose_name='Data Snapshot')),
                ('flags_at_generation', models.JSONField(blank=True, default=list, help_text='Warning/info validation flags active when draft was generated.', verbose_name='Flags at Generation Time')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('ipo_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_drafts', to='trinity.ipoworkspace')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Section Draft',
                'verbose_name_plural': 'Section Drafts',
                'db_table': 'trinity_section_drafts',
                'ordering': ('section', '-version'),
                'unique_together': {('ipo_workspace', 'section', 'version')},
            },
        ),
    ]
