# Generated by Django 4.2.30 on 2026-07-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trinity', '0003_sectiondraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='useofproceeds',
            name='repayment_counterparty_id',
            field=models.UUIDField(blank=True, help_text='Reference to existing ShareholderEntry or RelatedPartyTransaction party UUID', null=True, verbose_name='Repayment Counterparty ID'),
        ),
    ]
